### ISSUE TITLE
calculating server side permissions

### ISSUE THREAD

**Issue by Asafweiz** [starandtina/backend-interview-questions#2]
Hi all!

Headers coming back from server response shows two definitions:

1.       Access-Control-Allow-Origin: *.

2.       Content-Security-Policy: default-src 'self'

 Eventually, after calculating all the permissions that the server gives to the client the result is that I can *upload* any content type (JavaScript, Images, CSS, Fonts, AJAX requests……) from the same Origin (that’s the "self" limitation) end make *queries* from any Origin.

Correct?

**Comment by starandtina** [comment]
@Asafweiz Please refer to the links below.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
